# Config file for Air

# Root directory for http
root_dir = "."

# List of build excludes
excludes = ["tmp", "vendor"]

# Watch list
[[watch]]
name = "go"
path = "."

[[watch]]
name = "api"
path = "./api"

[[watch]]
name = "handlers"
path = "./handlers"

[[watch]]
name = "static"
path = "./static"

[[watch]]
name = "templates"
path = "./templates"

[log]
level = "debug"

# Build configuration
[build]
# Binaries output path (you may adjust this as needed)
bin = "tmp/main"

# Build command, use 'go build' with output to the defined 'bin' path
cmd = "go build -o tmp/main ."

# Run configuration
[run]
# Command to run the built binary
cmd = "./tmp/main"
